### ISSUE TITLE
[bug] Disconnect Button Partially Hidden Under Android System Navigation Panel

### ISSUE THREAD

**Issue by AndrewKravchenko** [reown-com/appkit#2542] opened 2024-07-15 14:48 UTC
### Link to minimal reproducible example

n/a

### Summary

The Disconnect button in the wallet connection interface is partially obscured by the Android system navigation panel, making it difficult for users to access the button properly. 

Steps to Reproduce:

- Connect your wallet using MetaMask on an Android device.
- Observe the position of the Disconnect button in the wallet connection interface.

![bug](https://github.com/user-attachments/assets/abf3204d-099a-40c3-8a62-af665d290152)

### List of related npm package versions

    "@web3modal/wagmi": "^5.0.6",

**Comment by rtomas** [comment] 2024-12-11 15:26
@AndrewKravchenko is this still happening to you ? 
can you test this on https://appkit-lab.reown.com/

I can't reproduce it

**Comment by rtomas** [comment] 2024-12-17 12:06
closing it ... seems solve since i can't reproduce it. please more info about the version that your are using in a new issue.

**Closed by rtomas** 2024-12-17 12:06 UTC
Labels: bug, needs review
