### ISSUE TITLE
[bug] Nuxt: Error: Failed to disconnect (only after page refresh)

### ISSUE THREAD

**Issue by creazy231** [reown-com/appkit#3383] opened 2024-12-03 12:22 UTC
### Link to minimal reproducible example

Reproducible using code from summary

### Summary

```js
import { useDisconnect } from "@reown/appkit/vue";
const { disconnect } = useDisconnect();
```

Calling the `disconnect` function results in the following console error:

```
Error: Failed to disconnect
```

but **only** if you refresh the page and it automatically reconnects your wallet. If you don't refresh the page, the disconnect works as expected.

### List of related npm package versions

```
    "@reown/appkit": "^1.5.3",
    "@reown/appkit-adapter-wagmi": "^1.5.3",
    "@tanstack/vue-query": "^5.62.2",
    "@wagmi/vue": "^0.0.68",
    ...
    "nuxt": "^3.14.1592",
    "vue": "^3.5.13",
```

### Node.js Version

v22.6.0

### Package Manager

yarn@4.5.3

**Comment by creazy231** [comment] 2024-12-03 13:08
When using
```js
const wagmiAdapter = new WagmiAdapter({
  ssr: true,
  networks,
  projectId,
});
```
disconnecting wallet works but then I'm not able to login again using MetaMask since it doesn't show up as installed.

**Comment by CryptoDevFr** [comment] 2024-12-03 21:56
Same here. Disconnecting works now on refreshing page but I can't use metamask through browser since it doesn't show installed...

**Comment by mubarak117136** [comment] 2024-12-06 01:31
Same here for me. ssr true config not found the browser meta mask.

**Comment by arein** [comment] 2024-12-11 08:08
@mubarak117136 @CryptoDevFr @creazy231 - ACK

**Comment by Mimis** [comment] 2024-12-11 20:56
same here: setting ssr to true metamask, is not detected as installed in broswer

**Comment by arein** [comment] 2024-12-12 02:45
@mubarak117136 @CryptoDevFr @creazy231 @Mimis - mind upgrading to v1.6.0 and checking if the issue persists?

**Comment by arein** [comment] 2024-12-12 06:59
Gotcha - I think @enesozturk is working on this with a fix slated for next week - is this a blocker @Mimis ? What app are you building?

**Comment by rtomas** [comment] 2024-12-13 01:58
@mubarak117136 @CryptoDevFr @creazy231 @Mimis 
Hi all ! 
I created a small example that works well for me.
can you double check and tell if someone is missing in my example ?

https://github.com/rtomas/appkit-nuxt-wagmi-example
https://appkit-nuxt-wagmi-example-test.vercel.app/

**Comment by Mimis** [comment] 2024-12-13 07:41
Thanks a lot @rtomas and @arein.  I can confirm that works in my end. I was missing the wagmi code dependency and the wagmi configuration. I thought the wagmi adaprt confiug would be enough

Would very usefull to add this example in your examples repo

**Comment by Mimis** [comment] 2024-12-13 07:50
i am building a  crypto payment app

**Comment by mubarak117136** [comment] 2024-12-15 13:14
Hi, @rtomas it works for me also. thanks a lot

**Comment by rtomas** [comment] 2024-12-17 12:04
Closing the issue, but please contact me to devrel -> https://reown.com/contact or my personal links to tell us what your are building with more details 💯

**Comment by rtomas** [comment] 2024-12-17 12:04
I will be adding the example to our repository soon !

**Closed by rtomas** 2024-12-17 12:04 UTC
Labels: bug
