### ISSUE TITLE
[bug] vue3 Could not resolve "@reown/appkit-siwe" node_modules/use-sync-external-store/cjs/use-sync-external-store-shim.development.js:26:30:

### ISSUE THREAD

**Issue by NicholasJupiter** [reown-com/appkit#3327] opened 2024-11-25 12:27 UTC
### Link to minimal reproducible example

https://codesandbox.io/p/devbox/nqvjt7?file=%2Fpackage.json%3A12%2C1-19%2C27

### Summary

  ➜  press h + enter to show help
✘ [ERROR] Could not resolve "@reown/appkit-siwe"

    node_modules/@reown/appkit/dist/esm/src/client.js:382:42:
      382 │                 const siwe = await import('@reown/appkit-siwe');
          ╵                                           ~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@reown/appkit-siwe" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle. You can also add ".catch()" here to
  handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "react"

    node_modules/use-sync-external-store/cjs/use-sync-external-store-shim.development.js:26:30:
      26 │           var React = require('react');
         ╵                               ~~~~~~~

  You can mark the path "react" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle. You can also surround this "require" call with
  a try/catch block to handle this failure at run-time instead of bundle-time.

12:26:10 PM [vite] error while updating dependencies:
Error: Build failed with 2 errors:
node_modules/@reown/appkit/dist/esm/src/client.js:382:42: ERROR: Could not resolve "@reown/appkit-siwe"
node_modules/use-sync-external-store/cjs/use-sync-external-store-shim.development.js:26:30: ERROR: Could not resolve "react"
    at failureErrorWithLog (/project/workspace/node_modules/esbuild/lib/main.js:1472:15)
    at /project/workspace/node_modules/esbuild/lib/main.js:945:25
    at /project/workspace/node_modules/esbuild/lib/main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### List of related npm package versions

    "@reown/appkit": "^1.5.1",
    "@reown/appkit-adapter-wagmi": "^1.5.1",
    "@tanstack/vue-query": "^5.61.3",
    "@wagmi/vue": "^0.0.65",
    "pinia": "^2.2.6",
    "viem": "^2.21.50",
    "vue": "^3.4.15",
    "vue-router": "^4.4.5"

**Comment by NicholasJupiter** [comment] 2024-11-25 12:27
What? After the overhaul, a bunch of bugs.

**Comment by arein** [comment] 2024-11-25 13:37
thanks for reporting @NicholasJupiter - we'll take a look shortly

**Comment by arein** [comment] 2024-11-25 13:42
@NicholasJupiter we've root caused this and will shortly release a fix

**Comment by arein** [comment] 2024-11-25 13:48
It's been merged and we're releasing a new version with the fix today - pls stay tuned @NicholasJupiter

**Closed by arein** 2024-11-25 13:48 UTC
Labels: bug, needs review

**Comment by creazy231** [comment] 2024-11-26 13:35
Any updates on this? Or is there any ETA? Really appreciate your work guys

**Comment by microHoffman** [comment] 2024-11-29 06:45
@arein the issue is still happening, even on latest 1.5.3 canary version

**Comment by arein** [comment] 2024-11-29 07:11
@microHoffman - @enesozturk is taking a look today

@creazy231 - we've released a new version that @enesozturk said fixes this - but possibly there are still some issues - can you check if it works for you?

**Comment by enesozturk** [comment] 2024-11-29 16:18
Hey @microHoffman @creazy231 I'm trying this on separate Vue app with `1.5.3` with fresh install and I cannot reproduce it. Did you try doing clean install? Your package managers may conflict with the previously installed versions. Plus, may I ask your package manager and version of it?

**Comment by creazy231** [comment] 2024-12-02 17:31
Hey @enesozturk I'm using latest Nuxt 3 inside a mono repo with `yarn v4.5.3` and `turbo@2.3.3`
