### ISSUE TITLE
[bug] Appkit calls a lot of request to The Blockchain API on zkSync causing The 429 error with too many requests.

### ISSUE THREAD

**Issue by ZkSwapFinance** [reown-com/appkit#3294] opened 2024-11-21 09:23 UTC
### Link to minimal reproducible example

https://www.zkswap.finance

### Summary

Dear Reown Team,

Our dApp has been using Web3Modal (AppKit) with Next.js for a long time without any issues. However, today we encountered a problem: the "429 Too Many Requests" error. 

We are using the ZKSync Era RPC, but we’re unsure why there are so many requests being sent to the Blockchain API from https://rpc.walletconnect.org/v1/?chainId=eip155%3A324&projectId=80f7c0bfe8da536240a51fe4df7277fc

The number of requests from our website has reached 7.1M, which led to WalletConnect blocking our dApp. 

Could you help us understand why this is happening and how we can resolve it? Specifically, we would like to know how to disable the Blockchain API so the dApp returns to normal. Is this an issue with our integration, or is it a bug on WalletConnect's side? 

Thank you for your help!

Website: https://www.zkswap.finance/swap

### List of related npm package versions

Version 1.1.2

**Comment by ionmig** [comment] 2024-11-21 13:05
Hi,

we have exactly the same issue since 2 days on base chain, tried to update packages to latest versions, no success. Was working properly over the past 3 months.

also;
- removed and reauthenticated domains on dashboard
- tried to verify with txt file on well-known
- used older packages to bypass


    "@reown/appkit": "^1.5.0",
    "@reown/appkit-adapter-wagmi": "^1.5.0",
    "@reown/appkit-siwe": "^1.5.0",
    "viem": "^2.21.48",
    "wagmi": "^2.13.0"
    
    
https://rpc.walletconnect.org/v1/?chainId=eip155%3A8453&projectId=XXX

**Comment by rtomas** [comment] 2024-11-22 15:28
@ZkSwapFinance @ionmig are you using AppKit latest version ? 
Do you have a site to double check it ?

https://www.zkswap.finance/ is not using AppKit.

**Comment by ionmig** [comment] 2024-11-22 15:36
> @ZkSwapFinance @ionmig are you using AppKit latest version ? Do you have a site to double check it ?
> 
> https://www.zkswap.finance/ is not using AppKit.

nitrodome.com

"@reown/appkit": "^1.5.0",
"@reown/appkit-adapter-wagmi": "^1.5.0",
"@reown/appkit-siwe": "^1.5.0",
"viem": "^2.21.48",
"wagmi": "^2.13.0"

**Comment by rtomas** [comment] 2024-11-22 16:15
@ionmig which version are you using in this link ?

**Comment by rtomas** [comment] 2024-11-22 19:55
@ZkSwapFinance Can you double check if all the Allowed Origins that are in cloud are yours ?

**Comment by rtomas** [comment] 2024-11-22 22:12
@ZkSwapFinance are you using AppKit ?

You have 5m calls to `eth_getBlockByNumber` in 2days ? do you know why ? 
Do you have a to reproduce example to view this calls ?

**Comment by ZkSwapFinance** [comment] 2024-11-23 02:33
> @ZkSwapFinance @ionmig are you using AppKit latest version ? Do you have a site to double check it ?
> 
> https://www.zkswap.finance/ is not using AppKit.

The AppKit version is 1.1.2. At the moment, we do not have a site for testing it.

We updated another version of the wallet connect kit to ensure users are not interrupted while using the product.

**Comment by ZkSwapFinance** [comment] 2024-11-23 02:39
> @ZkSwapFinance are you using AppKit ?
> 
> You have 5m calls to `eth_getBlockByNumber` in 2days ? do you know why ? Do you have a to reproduce example to view this calls ?

Yes, I see. We do not know why it calls so much. The old version we used, React Kit, was perfect and smooth

**Comment by ZkSwapFinance** [comment] 2024-11-23 02:41
> > @ZkSwapFinance @ionmig are you using AppKit latest version ? Do you have a site to double check it ?
> > https://www.zkswap.finance/ is not using AppKit.
> 
> The AppKit version is 1.1.2. At the moment, we do not have a site for testing it.
> 
> We updated another version of the wallet connect kit to ensure users are not interrupted while using the product.

We 

> @ZkSwapFinance are you using AppKit ?
> 
> You have 5m calls to `eth_getBlockByNumber` in 2days ? do you know why ? Do you have a to reproduce example to view this calls ?

We will update the test site for you regarding this bug today.

**Comment by ZkSwapFinance** [comment] 2024-11-23 05:45
> @ZkSwapFinance are you using AppKit ?
> 
> You have 5m calls to `eth_getBlockByNumber` in 2days ? do you know why ? Do you have a to reproduce example to view this calls ?

Here is test site: https://reown.zkswap.finance/

**Comment by ionmig** [comment] 2024-11-29 12:40
> > @ZkSwapFinance @ionmig are you using AppKit latest version ? Do you have a site to double check it ?
> > https://www.zkswap.finance/ is not using AppKit.
> 
> https://nitrodome.com
> 
> "@reown/appkit": "^1.5.0", "@reown/appkit-adapter-wagmi": "^1.5.0", "@reown/appkit-siwe": "^1.5.0", "viem": "^2.21.48", "wagmi": "^2.13.0"

Is there an update? the issue is still there.
Please see also attached.
![error](https://github.com/user-attachments/assets/b55cc80b-8b27-463e-9ca8-bad7e7dcebcc)

**Comment by ionmig** [comment] 2024-11-30 12:33
@rtomas @lukaisailovic @ZkSwapFinance @pkieltyka 

got it resolved by removing the connectors from wagmiAdapter.

const connectors: CreateConnectorFn[] = []
connectors.push(walletConnect({ projectId, metadata, showQrModal: false }))
connectors.push(injected({ shimDisconnect: true }))
connectors.push(.....

something i left in after migrating to appkit.

**Comment by ZkSwapFinance** [comment] 2024-11-30 13:45
> @rtomas @lukaisailovic @ZkSwapFinance @pkieltyka
> 
> got it resolved by removing the connectors from wagmiAdapter.
> 
> const connectors: CreateConnectorFn[] = [] connectors.push(walletConnect({ projectId, metadata, showQrModal: false })) connectors.push(injected({ shimDisconnect: true })) connectors.push(.....
> 
> something i left in after migrating to appkit.

Thank you for the information; we will test it later

**Comment by arein** [comment] 2024-12-01 11:44
@ionmig I cannot reproduce

<img width="1721" alt="Screenshot 2024-12-01 at 7 43 51 PM" src="https://github.com/user-attachments/assets/cc36c9e5-1f78-42b0-a6bf-f09f6d85e61a">

**Comment by arein** [comment] 2024-12-01 11:44
@ZkSwapFinance can you please DM me? `cyberdrk` on Telegram

**Comment by ionmig** [comment] 2024-12-01 12:29
> @ionmig I cannot reproduce
> 
> <img alt="Screenshot 2024-12-01 at 7 43 51 PM" width="1721" src="https://private-user-images.githubusercontent.com/966091/391328875-cc36c9e5-1f78-42b0-a6bf-f09f6d85e61a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNTY0MTksIm5iZiI6MTczMzA1NjExOSwicGF0aCI6Ii85NjYwOTEvMzkxMzI4ODc1LWNjMzZjOWU1LTFmNzgtNDJiMC1hNmJmLWYwOWY2ZDg1ZTYxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxMjI4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDAxMjg5ODdmODAwMTMyY2MzY2RmMTJlNWRlOTVjZTIwNTQzOTI5Yjc1NDVlYTUzNmE4ZGZmZjJlZjNhMmYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.C0LZqrAv88RKG886mMM4YicUgcybaLt0zhAlod6W_4Q">

Ofc you cant, we solved it! See my last comment.

**Comment by rtomas** [comment] 2024-12-02 12:45
@ZkSwapFinance Please confirm if this works for you so we can close the issue.
Thanks

**Comment by ZkSwapFinance** [comment] 2024-12-03 02:16
> @ZkSwapFinance Please confirm if this works for you so we can close the issue. Thanks

Not yet. If it works, we will close this issue. Thank you!

**Comment by arein** [comment] 2024-12-12 03:28
@ZkSwapFinance we've fixed an issue where sometimes the app provided RPC was not respected in version 1.6.0

our sincere apologies - thanks for using AppKit - I'll close the issue now - if you find any other issues in 1.6.0 or after please don't hesitate to reach out - I also left my telegram above

**Closed by arein** 2024-12-12 03:28 UTC
Labels: bug, needs review

**Comment by ZkSwapFinance** [comment] 2024-12-12 03:38
> @ZkSwapFinance we've fixed an issue where sometimes the app provided RPC was not respected in version 1.6.0
> 
> our sincere apologies - thanks for using AppKit - I'll close the issue now - if you find any other issues in 1.6.0 or after please don't hesitate to reach out - I also left my telegram above

Hello @arein ,

Thanks for the quick fix in version 1.6.0! We appreciate your support and will reach out if needed.
