### ISSUE TITLE
[bug] Modal allows to switch to an unsupported network

### ISSUE THREAD

**Issue by vanyasav** [reown-com/appkit#3129] opened 2024-10-19 19:15 UTC
### Link to minimal reproducible example

https://github.com/vanyasav/angular-reown-wagmi/tree/switch_network

### Summary

1. Choose unsupported network in metamask
2. Connect wallet
3. Metamask asks to change network
4. Change network
5. Connection successful
6. Change to an unsported network in metamask
7. Expected modal to show a warning like it used to do in web3modal

[Screencast from 19-10-2024 21:08:25.webm](https://github.com/user-attachments/assets/f6401e95-25de-4a28-899e-eaa874031cd8)

### List of related npm package versions

```
    "@reown/appkit": "^1.1.6",
    "@reown/appkit-adapter-wagmi": "^1.1.6",
```

**Comment by radchenk0** [comment] 2024-10-29 12:52
Faced with the same issue, but slightly different.
In my case, if I switch to a network within wallet manually that the dapp doesn't support (not configured), "Networks" view shows the previous chain I was on. And what makes situation even worth - it doesnt allow switching back to the chain the dapp supports via "Networks" view, just nothing happens

**Comment by lyfmantle** [comment] 2024-10-30 02:59
yes, on the previous version, if switched chain on metamask, we can switch to the current chain by opening the modal, but now it just can't, we must disconnect it to reconnect

**Comment by vanyasav** [comment] 2024-11-12 08:19
@rtomas still an issue in 1.3.2

**Comment by rtomas** [comment] 2024-11-12 20:53
https://linear.app/reown/issue/APKT-1422/[bug]-networks-view-doesnt-reflect-current-chain-if-i-switched-within

**Comment by arein** [comment] 2024-12-12 04:09
@vanyasav @lyfmantle @radchenk0 our sincere apologies - closing as dupe of https://github.com/reown-com/appkit/issues/3340

What are y'all building?

Also why do you need the unsupported network option?

**Closed by arein** 2024-12-12 04:09 UTC
Labels: bug
