### ISSUE TITLE
[bug] GET return 404 from https://rpc.walletconnect.com/v1/profile/reverse/xxx

### ISSUE THREAD

**Issue by tuannx** [reown-com/appkit#2347] opened 2024-06-02 00:15 UTC
### Link to minimal reproducible example

[https://web3modal-mre.vercel.app/](https://web3modal-mre.vercel.app/)

### Summary

Create new react ts with web3modal ethers.

Connect to smartwallet base testnet:
  chainId: 84532,
  name: "Base Sepolia",
  currency: "ETH",
  explorerUrl: "[https://sepolia-explorer.base.org](https://sepolia-explorer.base.org)",
  rpcUrl: "[https://sepolia.base.org](https://sepolia.base.org)",

After login got error 404:
GET [https://rpc.walletconnect.com/v1/profile/reverse/0x14338152970B7B9A24092382e4B2e9B78Ba13D65?projectId=28e14a91201028f94cee88eb9da0a227](https://rpc.walletconnect.com/v1/profile/reverse/0x14338152970B7B9A24092382e4B2e9B78Ba13D65?projectId=28e14a91201028f94cee88eb9da0a227) 404 (Not Found)

Potential problem: Smartwallet create smart contract address instead of normal wallet address.

smartwallet address on Base testnet: 0x14338152970B7B9A24092382e4B2e9B78Ba13D65

code: [https://github.com/tuannx/web3modal-mre](https://github.com/tuannx/web3modal-mre)

### List of related npm package versions

```
"@testing-library/jest-dom": "^5.17.0",
"@testing-library/react": "^13.4.0",
"@testing-library/user-event": "^13.5.0",
"@types/jest": "^27.5.2",
"@types/node": "^16.18.97",
"@types/react": "^18.3.3",
"@types/react-dom": "^18.3.0",
"@web3modal/ethers": "^4.2.3",
"ethers": "^6.12.1",
"react": "^18.3.1",
"react-dom": "^18.3.1",
"react-scripts": "5.0.1",
"typescript": "^4.9.5",
"web-vitals": "^2.1.4"
```

**Comment by peteAhn** [comment] 2024-06-20 05:24
Same here

**Comment by kr-arunp** [comment] 2024-06-26 04:57
same issue here

**Comment by VajraK** [comment] 2024-07-02 09:53
also, on mainnet!

**Comment by chris13524** [comment] 2024-07-07 00:06
Is something not functioning properly or are you guys just seeing this error in the console?

**Comment by whichghost** [comment] 2024-07-07 02:57
it happens on https://lab.web3modal.com/ with rabby wallet on chrome

**Comment by ZachHandley** [comment] 2024-07-08 21:50
So, as of now, it's been 5 weeks with seemingly no activity or assigned user, I messaged about it in Discord and was ignored, is it super borked, not a priority, gonna take another week, can we get some communication here?

**Comment by chris13524** [comment] 2024-07-08 21:54
@ZachHandley I replied to the thread above

Is something broken or not-functional with the UI or SDK?

Or is the concern only that there are errors in the console? Our API returns 404s when things don't exist, but this is expected/normal behavior.

**Comment by ZachHandley** [comment] 2024-07-08 22:08
Yeah my balances don't show, which isn't a gigantic deal, though it definitely should be fixed cause it's not very clear, but I'm also curious what the profile is and how to reduce the 2-4 errors in the console

**Comment by chris13524** [comment] 2024-07-08 22:47
I loaded the example from the issue description and my balance displays fine:

<img width="458" alt="image" src="https://github.com/WalletConnect/web3modal/assets/1979423/d7956e50-5e47-4b0d-bd3f-212ecfd1069b">

`/profile` is for loading information about ENS name registrations, it is unrelated to the balance request.

@ZachHandley can you please open up a new issue/discussion for your balance not showing issue and include a MRE?

---

We are planning a new API revision that will remove the use of 4xx's across our APIs for normal conditions, which will avoid the console errors seen here. Tracking issue [here](https://github.com/WalletConnect/web3modal/issues/2522).

Closing this issue as it seems like the problem is exclusively the console errors and no functionality is broken.

**Comment by glitch-txs** [comment] 2024-07-22 10:01
> Closing this issue as it seems like the problem is exclusively the console errors and no functionality is broken.

AppKit is still sending an invalid request so I think still needs fixing if I'm not mistaken.

**Comment by chris13524** [comment] 2024-07-22 20:17
> AppKit is still sending an invalid request so I think still needs fixing if I'm not mistaken.

@glitch-txs please elaborate on what is broken

**Comment by Victor-Salomon** [comment] 2024-07-26 13:13
@chris13524 @glitch-txs I'm following up with the current issue. 

It's actually related to the issue https://github.com/WalletConnect/web3modal/issues/1888 I'm expecting a response for, if possible. Thanks a lot for your help in advance. 
I'm happy to highlight or elaborate on the issue if needed. 

Thanks!

**Comment by theMacAli** [comment] 2024-09-05 02:54
i'm having the same issue. Any update or solution?

**Comment by rtomas** [comment] 2024-12-11 14:12
This is not longer an issue.  Please update to latest.

**Closed by rtomas** 2024-12-11 14:12 UTC
Labels: bug
