### ISSUE TITLE
[bug] datadog sends logs even analytics are disabled in localhost

### ISSUE THREAD

**Issue by kevtechi** [reown-com/appkit#2914] opened 2024-09-24 12:25 UTC
### Link to minimal reproducible example

https://github.com/techi-solutions/soliditree/blob/main/services/walletConnect/context/index.tsx

### Summary

Example URL that is called: `https://browser-intake-datadoghq.com/api/v2/logs?ddsource=...`

Analytics should be separated into its own package. Default should be off in EU.

### List of related npm package versions

latest

**Comment by brenopolanski** [comment] 2024-09-26 01:36
I have the same issue +1

**Comment by 0xonerb** [comment] 2024-09-26 01:37
I have the same issue +1

**Comment by rtomas** [comment] 2024-10-15 02:23
Closing because the issue is solved. But please reopen it if you see it again.

**Closed by rtomas** 2024-10-15 02:23 UTC
Labels: bug, needs review
