### ISSUE TITLE
[bug] SwitchNetwork and allowUnsupportedChain doesn't work on AppKit + Ethers

### ISSUE THREAD

**Issue by youngancient** [reown-com/appkit#3124] opened 2024-10-19 03:09 UTC
### Link to minimal reproducible example

https://appkit-lab.reown.com/library/ethers/

### Summary

After adding a custom network called liskSepoliaNetwork, and setting allowUnsupportedChain to false here:
![image](https://github.com/user-attachments/assets/72b7169f-671a-4cd4-b81f-bb5c46504374)

I have my contract deployed on liskSepolia.
The modal allows the user to connect to an unsupportedChain (e.g Sepolia), and even sign transactions on that unsupported chain without prompting the user to switch networks to the supportedChain

### List of related npm package versions

"@reown/appkit": "^1.0.4",
 "@reown/appkit-adapter-ethers": "^1.0.4",

**Comment by arein** [comment] 2024-12-12 04:10
Closing as dupe of https://github.com/reown-com/appkit/issues/3129

**Closed by arein** 2024-12-12 04:10 UTC
Labels: bug, needs review
